package com.newt.dao.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.newt.dao.model.Product;
import com.newt.dao.model.ProductExample;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Feb 27 12:09:53 IST 2016
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Feb 27 12:09:53 IST 2016
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Feb 27 12:09:53 IST 2016
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Feb 27 12:09:53 IST 2016
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Feb 27 12:09:53 IST 2016
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Feb 27 12:09:53 IST 2016
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sat Feb 27 12:09:53 IST 2016
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);
    
    List<Product> selectAllProduct();
    Product selectProductById(int id);
    void insertProduct(Product orderDetail);
    void updateProduct(Product orderDetail);
    void deleteProduct(int id);
}