package com.newt.dao.model;

import java.io.Serializable;

public class Product implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product.ID
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product.NAME
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product.ISBN
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	private Integer isbn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product.ID
	 *
	 * @return the value of product.ID
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product.ID
	 *
	 * @param id
	 *            the value for product.ID
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product.NAME
	 *
	 * @return the value of product.NAME
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product.NAME
	 *
	 * @param name
	 *            the value for product.NAME
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product.ISBN
	 *
	 * @return the value of product.ISBN
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	public Integer getIsbn() {
		return isbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product.ISBN
	 *
	 * @param isbn
	 *            the value for product.ISBN
	 *
	 * @mbggenerated Sat Feb 27 12:09:53 IST 2016
	 */
	public void setIsbn(Integer isbn) {
		this.isbn = isbn;
	}
}